Update to the interface IF-DREAM-O-AddProduct, and associated test.
The previous commit was missing most of the updates.  See README.md
for details on using the intefaces, tests and for configuring/running
the Ingestion Engine.

diff --git a/ie b/ie
--- a/ie
+++ b/ie
@@ -1,6 +1,25 @@
-#( cd ../ngEO-download-manager; ./start_dm.sh )
-if [[ ! -f ingestion/static/db/dream.db ]]
+#!/usr/bin/env sh
+
+INGESTION_DIR=ingestion
+
+ie_dd=$(dirname $0)
+
+ing_dir=$ie_dd/$INGESTION_DIR
+if [[ ! -d $ing_dir ]]
+then
+  echo "FATAL: missing subdirectory '$ing_dir', exiting"
+  exit 2
+fi
+
+cd $ie_dd
+
+if [[ ! -d $INGESTION_DIR/static/db ]]
+then
+  mkdir $INGESTION_DIR/static/db
+fi
+
+if [[ ! -f $INGESTION_DIR/static/db/dream.db ]]
 then
   ./manage.py syncdb --noinput
 fi
-./manage.py runserver
+./manage.py runserver $1
